import Navbar from '@/components/navbar'
import React from 'react'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

type RootLayoutProps = {
	children: React.ReactNode
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
	return (
		<React.Fragment>
			<Navbar />
			{children}
		</React.Fragment>
	)
}

export default RootLayout
